// The job panel's Run bar: who generated the stored result, and whether the
// coach is offered Run / Re-run. The server is what refuses a view-only coach;
// this pins that the panel does not OFFER the button to one.

import { describe, it, expect, afterEach, vi } from "vitest"
import { render, screen, cleanup, fireEvent } from "@testing-library/react"
import { RunBar } from "./JobDetailPanel"

vi.mock("../../../../../lib/supabase-browser", () => ({
  getSupabaseBrowser: () => ({ auth: { getSession: async () => ({ data: { session: { access_token: "t" } } }) } }),
}))

afterEach(cleanup)

const base = { kind: "Positioning" as const, running: false, error: null, onRun: () => {} }

describe("RunBar", () => {
  it("offers Run when nothing has been generated", () => {
    render(<RunBar {...base} hasResult={false} by={null} canRun />)
    expect(screen.getByRole("button", { name: "Run Positioning" })).toBeTruthy()
    expect(screen.queryByText(/Generated by/)).toBeNull()
  })

  it("says a coach generated it, and offers Re-run", () => {
    render(<RunBar {...base} hasResult by="coach" canRun />)
    expect(screen.getByText("Generated by a coach")).toBeTruthy()
    expect(screen.getByRole("button", { name: "Re-run Positioning" })).toBeTruthy()
  })

  it("reads a run from before attribution (null) as the client's", () => {
    render(<RunBar {...base} hasResult by={null} canRun />)
    expect(screen.getByText("Generated by the client")).toBeTruthy()
  })

  it("offers no button to a coach who cannot run, but still says who made it", () => {
    render(<RunBar {...base} hasResult by="client" canRun={false} />)
    expect(screen.queryByRole("button")).toBeNull()
    expect(screen.getByText("Generated by the client")).toBeTruthy()
  })

  it("renders nothing at all with no result and no right to run", () => {
    const { container } = render(<RunBar {...base} hasResult={false} by={null} canRun={false} />)
    expect(container.innerHTML).toBe("")
  })

  it("calls onRun, and shows the server's error", () => {
    const onRun = vi.fn()
    render(<RunBar {...base} kind="Cover Letter" hasResult={false} by={null} canRun onRun={onRun} error="This job has no JobFit run yet" />)
    fireEvent.click(screen.getByRole("button", { name: "Run Cover Letter" }))
    expect(onRun).toHaveBeenCalledTimes(1)
    expect(screen.getByRole("alert").textContent).toBe("This job has no JobFit run yet")
  })
})
