/* eslint-disable */
// AUTO-GENERATED by tests/generateFromCsv.ts — DO NOT EDIT BY HAND.

import type { JobSignalsV1, ProfileSignalsV1 } from "../src/types"

export const PROFILES: Record<string, ProfileSignalsV1> = {
  "P01": {
    "schema_version": "v1.0",
    "profile_id": "P01",
    "profile_type": "early_career",
    "targets": {
      "role_families": [
        "Consulting",
        "Strategy",
        "Business Analytics"
      ],
      "industries": [
        "General Business",
        "Consumer",
        "Tech"
      ],
      "domains": []
    },
    "education": {
      "degree_level": "bachelor",
      "majors": [],
      "grad_year": 2026,
      "gpa": 3.7
    },
    "experience": {
      "years_total_est": null,
      "years_relevant_est": 1.5,
      "internships_count": 2,
      "full_time_roles_count": 0
    },
    "skills_tools": {
      "tools": [
        "Excel",
        "PowerPoint",
        "Google Sheets",
        "SQL_basic",
        "Tableau_basic"
      ],
      "skills": [
        "Research",
        "Structured Problem Solving",
        "Stakeholder Communication",
        "Slide Development"
      ]
    },
    "certifications": [],
    "work_authorization": {
      "status": "us_citizen"
    },
    "location_preferences": {
      "preferred_regions": [
        "NYC"
      ],
      "remote_ok": true,
      "onsite_ok": true
    },
    "exposure_clusters": {
      "executed": [
        "Structured Problem Solving",
        "Research Synthesis",
        "Executive Communication",
        "Quantitative Analysis"
      ],
      "adjacent": [
        "Client Facing",
        "Light Project Management"
      ],
      "theoretical": []
    },
    "resume_fingerprint": "P01_FP"
  },
  "P02": {
    "schema_version": "v1.0",
    "profile_id": "P02",
    "profile_type": "early_career",
    "targets": {
      "role_families": [
        "Marketing",
        "Brand",
        "Growth"
      ],
      "industries": [
        "Lifestyle",
        "Sports",
        "Consumer"
      ],
      "domains": []
    },
    "education": {
      "degree_level": "bachelor",
      "majors": [],
      "grad_year": 2026,
      "gpa": 3.4
    },
    "experience": {
      "years_total_est": null,
      "years_relevant_est": 1,
      "internships_count": 1,
      "full_time_roles_count": 0
    },
    "skills_tools": {
      "tools": [
        "Canva",
        "Meta Ads",
        "Excel_basic",
        "Google Analytics_basic"
      ],
      "skills": [
        "Content Creation",
        "Campaign Coordination",
        "Social Analytics",
        "Copywriting"
      ]
    },
    "certifications": [],
    "work_authorization": {
      "status": "us_citizen"
    },
    "location_preferences": {
      "preferred_regions": [
        "Florida"
      ],
      "remote_ok": true,
      "onsite_ok": true
    },
    "exposure_clusters": {
      "executed": [
        "Content Creation",
        "Campaign Execution",
        "Social Analytics"
      ],
      "adjacent": [
        "Marketing Strategy",
        "Research Synthesis"
      ],
      "theoretical": [
        "SQL",
        "Advanced Analytics"
      ]
    },
    "resume_fingerprint": "P02_FP"
  },
  "P03": {
    "schema_version": "v1.0",
    "profile_id": "P03",
    "profile_type": "student",
    "targets": {
      "role_families": [
        "Data Analytics",
        "Business Analytics"
      ],
      "industries": [
        "Broad"
      ],
      "domains": []
    },
    "education": {
      "degree_level": "bachelor",
      "majors": [],
      "grad_year": 2027,
      "gpa": 3.2
    },
    "experience": {
      "years_total_est": null,
      "years_relevant_est": 0.2,
      "internships_count": 0,
      "full_time_roles_count": 0
    },
    "skills_tools": {
      "tools": [
        "Python_basic",
        "Excel_basic",
        "SQL_coursework",
        "PowerPoint"
      ],
      "skills": [
        "Statistics",
        "Data Cleaning",
        "Basic Modeling"
      ]
    },
    "certifications": [],
    "work_authorization": {
      "status": "us_citizen"
    },
    "location_preferences": {
      "preferred_regions": [],
      "remote_ok": true,
      "onsite_ok": true
    },
    "exposure_clusters": {
      "executed": [],
      "adjacent": [],
      "theoretical": [
        "Quantitative Analysis",
        "Data Analysis",
        "Dashboards"
      ]
    },
    "resume_fingerprint": "P03_FP"
  },
  "P04": {
    "schema_version": "v1.0",
    "profile_id": "P04",
    "profile_type": "early_career",
    "targets": {
      "role_families": [
        "Healthcare",
        "Clinical Ops"
      ],
      "industries": [
        "Healthcare Only"
      ],
      "domains": []
    },
    "education": {
      "degree_level": "bachelor",
      "majors": [],
      "grad_year": 2025,
      "gpa": null
    },
    "experience": {
      "years_total_est": null,
      "years_relevant_est": 1,
      "internships_count": 0,
      "full_time_roles_count": 1
    },
    "skills_tools": {
      "tools": [
        "Excel_basic",
        "Google Sheets",
        "Scheduling Tools"
      ],
      "skills": [
        "Patient Communication",
        "Operations Coordination"
      ]
    },
    "certifications": [],
    "work_authorization": {
      "status": "us_citizen"
    },
    "location_preferences": {
      "preferred_regions": [
        "NYC_Onsite_Only"
      ],
      "remote_ok": false,
      "onsite_ok": true
    },
    "exposure_clusters": {
      "executed": [
        "Client Facing",
        "Operations Coordination"
      ],
      "adjacent": [
        "Analysis Reporting"
      ],
      "theoretical": []
    },
    "resume_fingerprint": "P04_FP"
  },
  "P05": {
    "schema_version": "v1.0",
    "profile_id": "P05",
    "profile_type": "student",
    "targets": {
      "role_families": [
        "Consulting",
        "Business Analytics",
        "Strategy"
      ],
      "industries": [
        "General Business",
        "Tech"
      ],
      "domains": []
    },
    "education": {
      "degree_level": "in_progress",
      "majors": [],
      "grad_year": 2027,
      "gpa": 3.8
    },
    "experience": {
      "years_total_est": null,
      "years_relevant_est": 0.5,
      "internships_count": 1,
      "full_time_roles_count": 0
    },
    "skills_tools": {
      "tools": [
        "Excel",
        "PowerPoint",
        "Google Sheets",
        "SQL_basic"
      ],
      "skills": [
        "Research",
        "Structured Problem Solving",
        "Data Analysis",
        "Slide Development"
      ]
    },
    "certifications": [],
    "work_authorization": {
      "status": "us_citizen"
    },
    "location_preferences": {
      "preferred_regions": [
        "NYC"
      ],
      "remote_ok": true,
      "onsite_ok": true
    },
    "exposure_clusters": {
      "executed": [
        "Structured Problem Solving",
        "Data Analysis"
      ],
      "adjacent": [
        "Executive Communication",
        "Client Exposure"
      ],
      "theoretical": []
    },
    "resume_fingerprint": "P05_FP"
  }
}

export const JOBS: Record<string, JobSignalsV1> = {
  "J01": {
    "schema_version": "v1.0",
    "job_id": "J01",
    "normalized": {
      "title": "Consulting (entry)",
      "company": "GenericCo",
      "description": "Direct entry consulting role"
    },
    "role": {
      "seniority_hint": "entry",
      "employment_type_hint": "full_time",
      "role_families": [
        "Consulting"
      ]
    },
    "requirements": {
      "experience": {
        "min_years": null,
        "max_years": null,
        "is_explicit": false,
        "evidence": []
      },
      "education": {
        "is_required": false,
        "degree_level_min": "unknown",
        "fields_preferred": [],
        "evidence": []
      },
      "gpa": {
        "is_required": false,
        "minimum": null,
        "evidence": []
      },
      "certifications": {
        "required": [],
        "preferred": [],
        "evidence": []
      },
      "work_authorization": {
        "is_specified": false,
        "restriction_type": "unknown",
        "evidence": []
      },
      "location": {
        "mode": "remote",
        "is_hard_requirement": false,
        "evidence": []
      }
    },
    "skills_tools": {
      "tools_required": [
        "Excel",
        "PowerPoint"
      ],
      "tools_preferred": [],
      "skills_required": [],
      "skills_preferred": []
    },
    "responsibility_clusters": [
      "Structured Problem Solving",
      "Research Synthesis",
      "Executive Communication"
    ],
    "extraction_quality": {
      "confidence_overall": "high",
      "warnings": []
    }
  },
  "J02": {
    "schema_version": "v1.0",
    "job_id": "J02",
    "normalized": {
      "title": "Consulting (entry)",
      "company": "GenericCo",
      "description": "Requires 2 years experience"
    },
    "role": {
      "seniority_hint": "entry",
      "employment_type_hint": "full_time",
      "role_families": [
        "Consulting"
      ]
    },
    "requirements": {
      "experience": {
        "min_years": 2,
        "max_years": null,
        "is_explicit": true,
        "evidence": []
      },
      "education": {
        "is_required": false,
        "degree_level_min": "unknown",
        "fields_preferred": [],
        "evidence": []
      },
      "gpa": {
        "is_required": false,
        "minimum": null,
        "evidence": []
      },
      "certifications": {
        "required": [],
        "preferred": [],
        "evidence": []
      },
      "work_authorization": {
        "is_specified": false,
        "restriction_type": "unknown",
        "evidence": []
      },
      "location": {
        "mode": "remote",
        "is_hard_requirement": false,
        "evidence": []
      }
    },
    "skills_tools": {
      "tools_required": [
        "Excel",
        "PowerPoint"
      ],
      "tools_preferred": [],
      "skills_required": [],
      "skills_preferred": []
    },
    "responsibility_clusters": [
      "Structured Problem Solving",
      "Quantitative Analysis",
      "Executive Communication"
    ],
    "extraction_quality": {
      "confidence_overall": "high",
      "warnings": []
    }
  },
  "J03": {
    "schema_version": "v1.0",
    "job_id": "J03",
    "normalized": {
      "title": "Marketing (entry)",
      "company": "GenericCo",
      "description": "Entry marketing execution role"
    },
    "role": {
      "seniority_hint": "entry",
      "employment_type_hint": "full_time",
      "role_families": [
        "Marketing"
      ]
    },
    "requirements": {
      "experience": {
        "min_years": null,
        "max_years": null,
        "is_explicit": false,
        "evidence": []
      },
      "education": {
        "is_required": false,
        "degree_level_min": "unknown",
        "fields_preferred": [],
        "evidence": []
      },
      "gpa": {
        "is_required": false,
        "minimum": null,
        "evidence": []
      },
      "certifications": {
        "required": [],
        "preferred": [],
        "evidence": []
      },
      "work_authorization": {
        "is_specified": false,
        "restriction_type": "unknown",
        "evidence": []
      },
      "location": {
        "mode": "remote",
        "is_hard_requirement": false,
        "evidence": []
      }
    },
    "skills_tools": {
      "tools_required": [
        "Canva",
        "Meta Ads"
      ],
      "tools_preferred": [],
      "skills_required": [],
      "skills_preferred": []
    },
    "responsibility_clusters": [
      "Content Creation",
      "Campaign Execution",
      "Social Analytics"
    ],
    "extraction_quality": {
      "confidence_overall": "high",
      "warnings": []
    }
  },
  "J04": {
    "schema_version": "v1.0",
    "job_id": "J04",
    "normalized": {
      "title": "Data Analytics (intern)",
      "company": "GenericCo",
      "description": "Data internship"
    },
    "role": {
      "seniority_hint": "intern",
      "employment_type_hint": "internship",
      "role_families": [
        "Data Analytics"
      ]
    },
    "requirements": {
      "experience": {
        "min_years": null,
        "max_years": null,
        "is_explicit": false,
        "evidence": []
      },
      "education": {
        "is_required": false,
        "degree_level_min": "unknown",
        "fields_preferred": [],
        "evidence": []
      },
      "gpa": {
        "is_required": false,
        "minimum": null,
        "evidence": []
      },
      "certifications": {
        "required": [],
        "preferred": [],
        "evidence": []
      },
      "work_authorization": {
        "is_specified": false,
        "restriction_type": "unknown",
        "evidence": []
      },
      "location": {
        "mode": "remote",
        "is_hard_requirement": false,
        "evidence": []
      }
    },
    "skills_tools": {
      "tools_required": [
        "Python",
        "SQL",
        "Excel"
      ],
      "tools_preferred": [],
      "skills_required": [],
      "skills_preferred": []
    },
    "responsibility_clusters": [
      "Quantitative Analysis",
      "Data Analysis",
      "Dashboards"
    ],
    "extraction_quality": {
      "confidence_overall": "high",
      "warnings": []
    }
  },
  "J05": {
    "schema_version": "v1.0",
    "job_id": "J05",
    "normalized": {
      "title": "Consulting (senior)",
      "company": "GenericCo",
      "description": "Senior role requiring leadership"
    },
    "role": {
      "seniority_hint": "senior",
      "employment_type_hint": "full_time",
      "role_families": [
        "Consulting"
      ]
    },
    "requirements": {
      "experience": {
        "min_years": 4,
        "max_years": null,
        "is_explicit": true,
        "evidence": []
      },
      "education": {
        "is_required": false,
        "degree_level_min": "unknown",
        "fields_preferred": [],
        "evidence": []
      },
      "gpa": {
        "is_required": false,
        "minimum": null,
        "evidence": []
      },
      "certifications": {
        "required": [],
        "preferred": [],
        "evidence": []
      },
      "work_authorization": {
        "is_specified": false,
        "restriction_type": "unknown",
        "evidence": []
      },
      "location": {
        "mode": "onsite",
        "is_hard_requirement": true,
        "evidence": []
      }
    },
    "skills_tools": {
      "tools_required": [
        "Excel",
        "PowerPoint"
      ],
      "tools_preferred": [],
      "skills_required": [],
      "skills_preferred": []
    },
    "responsibility_clusters": [
      "Structured Problem Solving",
      "Client Leadership",
      "Project Ownership"
    ],
    "extraction_quality": {
      "confidence_overall": "high",
      "warnings": []
    }
  },
  "J06": {
    "schema_version": "v1.0",
    "job_id": "J06",
    "normalized": {
      "title": "Consulting (entry)",
      "company": "GenericCo",
      "description": "GPA 3.5 required"
    },
    "role": {
      "seniority_hint": "entry",
      "employment_type_hint": "full_time",
      "role_families": [
        "Consulting"
      ]
    },
    "requirements": {
      "experience": {
        "min_years": null,
        "max_years": null,
        "is_explicit": false,
        "evidence": []
      },
      "education": {
        "is_required": false,
        "degree_level_min": "unknown",
        "fields_preferred": [],
        "evidence": []
      },
      "gpa": {
        "is_required": true,
        "minimum": 3.5,
        "evidence": []
      },
      "certifications": {
        "required": [],
        "preferred": [],
        "evidence": []
      },
      "work_authorization": {
        "is_specified": false,
        "restriction_type": "unknown",
        "evidence": []
      },
      "location": {
        "mode": "remote",
        "is_hard_requirement": false,
        "evidence": []
      }
    },
    "skills_tools": {
      "tools_required": [
        "Excel",
        "PowerPoint"
      ],
      "tools_preferred": [],
      "skills_required": [],
      "skills_preferred": []
    },
    "responsibility_clusters": [
      "Structured Problem Solving",
      "Research Synthesis"
    ],
    "extraction_quality": {
      "confidence_overall": "high",
      "warnings": []
    }
  },
  "J07": {
    "schema_version": "v1.0",
    "job_id": "J07",
    "normalized": {
      "title": "Healthcare (entry)",
      "company": "GenericCo",
      "description": "Healthcare onsite only"
    },
    "role": {
      "seniority_hint": "entry",
      "employment_type_hint": "full_time",
      "role_families": [
        "Healthcare"
      ]
    },
    "requirements": {
      "experience": {
        "min_years": null,
        "max_years": null,
        "is_explicit": false,
        "evidence": []
      },
      "education": {
        "is_required": false,
        "degree_level_min": "unknown",
        "fields_preferred": [],
        "evidence": []
      },
      "gpa": {
        "is_required": false,
        "minimum": null,
        "evidence": []
      },
      "certifications": {
        "required": [],
        "preferred": [],
        "evidence": []
      },
      "work_authorization": {
        "is_specified": false,
        "restriction_type": "unknown",
        "evidence": []
      },
      "location": {
        "mode": "onsite",
        "is_hard_requirement": true,
        "evidence": []
      }
    },
    "skills_tools": {
      "tools_required": [
        "Scheduling Tools",
        "Excel"
      ],
      "tools_preferred": [],
      "skills_required": [],
      "skills_preferred": []
    },
    "responsibility_clusters": [
      "Operations Coordination",
      "Client Facing",
      "Scheduling"
    ],
    "extraction_quality": {
      "confidence_overall": "high",
      "warnings": []
    }
  },
  "J08": {
    "schema_version": "v1.0",
    "job_id": "J08",
    "normalized": {
      "title": "Aerospace Analytics (entry)",
      "company": "GenericCo",
      "description": "Requires aerospace domain"
    },
    "role": {
      "seniority_hint": "entry",
      "employment_type_hint": "full_time",
      "role_families": [
        "Aerospace Analytics"
      ]
    },
    "requirements": {
      "experience": {
        "min_years": 2,
        "max_years": null,
        "is_explicit": true,
        "evidence": []
      },
      "education": {
        "is_required": false,
        "degree_level_min": "unknown",
        "fields_preferred": [],
        "evidence": []
      },
      "gpa": {
        "is_required": false,
        "minimum": null,
        "evidence": []
      },
      "certifications": {
        "required": [],
        "preferred": [],
        "evidence": []
      },
      "work_authorization": {
        "is_specified": false,
        "restriction_type": "unknown",
        "evidence": []
      },
      "location": {
        "mode": "remote",
        "is_hard_requirement": false,
        "evidence": []
      }
    },
    "skills_tools": {
      "tools_required": [
        "Python",
        "SQL"
      ],
      "tools_preferred": [],
      "skills_required": [],
      "skills_preferred": []
    },
    "responsibility_clusters": [
      "Aerospace Modeling",
      "Maintenance Planning",
      "Advanced Analytics"
    ],
    "extraction_quality": {
      "confidence_overall": "high",
      "warnings": []
    }
  },
  "J09": {
    "schema_version": "v1.0",
    "job_id": "J09",
    "normalized": {
      "title": "Business Analytics (entry)",
      "company": "GenericCo",
      "description": "Moderate business analytics role"
    },
    "role": {
      "seniority_hint": "entry",
      "employment_type_hint": "full_time",
      "role_families": [
        "Business Analytics"
      ]
    },
    "requirements": {
      "experience": {
        "min_years": 1,
        "max_years": null,
        "is_explicit": true,
        "evidence": []
      },
      "education": {
        "is_required": false,
        "degree_level_min": "unknown",
        "fields_preferred": [],
        "evidence": []
      },
      "gpa": {
        "is_required": false,
        "minimum": null,
        "evidence": []
      },
      "certifications": {
        "required": [],
        "preferred": [],
        "evidence": []
      },
      "work_authorization": {
        "is_specified": false,
        "restriction_type": "unknown",
        "evidence": []
      },
      "location": {
        "mode": "remote",
        "is_hard_requirement": false,
        "evidence": []
      }
    },
    "skills_tools": {
      "tools_required": [
        "Excel",
        "PowerPoint"
      ],
      "tools_preferred": [],
      "skills_required": [],
      "skills_preferred": []
    },
    "responsibility_clusters": [
      "Quantitative Analysis",
      "Research Synthesis",
      "Reporting"
    ],
    "extraction_quality": {
      "confidence_overall": "high",
      "warnings": []
    }
  },
  "J10": {
    "schema_version": "v1.0",
    "job_id": "J10",
    "normalized": {
      "title": "Marketing (entry)",
      "company": "GenericCo",
      "description": "Marketing analytics hybrid"
    },
    "role": {
      "seniority_hint": "entry",
      "employment_type_hint": "full_time",
      "role_families": [
        "Marketing"
      ]
    },
    "requirements": {
      "experience": {
        "min_years": 1,
        "max_years": null,
        "is_explicit": true,
        "evidence": []
      },
      "education": {
        "is_required": false,
        "degree_level_min": "unknown",
        "fields_preferred": [],
        "evidence": []
      },
      "gpa": {
        "is_required": false,
        "minimum": null,
        "evidence": []
      },
      "certifications": {
        "required": [],
        "preferred": [],
        "evidence": []
      },
      "work_authorization": {
        "is_specified": false,
        "restriction_type": "unknown",
        "evidence": []
      },
      "location": {
        "mode": "remote",
        "is_hard_requirement": false,
        "evidence": []
      }
    },
    "skills_tools": {
      "tools_required": [
        "Excel",
        "Google Analytics"
      ],
      "tools_preferred": [],
      "skills_required": [],
      "skills_preferred": []
    },
    "responsibility_clusters": [
      "Campaign Analysis",
      "Reporting",
      "Experimentation"
    ],
    "extraction_quality": {
      "confidence_overall": "high",
      "warnings": []
    }
  },
  "J11": {
    "schema_version": "v1.0",
    "job_id": "J11",
    "normalized": {
      "title": "Operations (entry)",
      "company": "GenericCo",
      "description": "General operations analyst"
    },
    "role": {
      "seniority_hint": "entry",
      "employment_type_hint": "full_time",
      "role_families": [
        "Operations"
      ]
    },
    "requirements": {
      "experience": {
        "min_years": 1,
        "max_years": null,
        "is_explicit": true,
        "evidence": []
      },
      "education": {
        "is_required": false,
        "degree_level_min": "unknown",
        "fields_preferred": [],
        "evidence": []
      },
      "gpa": {
        "is_required": false,
        "minimum": null,
        "evidence": []
      },
      "certifications": {
        "required": [],
        "preferred": [],
        "evidence": []
      },
      "work_authorization": {
        "is_specified": false,
        "restriction_type": "unknown",
        "evidence": []
      },
      "location": {
        "mode": "remote",
        "is_hard_requirement": false,
        "evidence": []
      }
    },
    "skills_tools": {
      "tools_required": [
        "Excel"
      ],
      "tools_preferred": [],
      "skills_required": [],
      "skills_preferred": []
    },
    "responsibility_clusters": [
      "Process Analysis",
      "Reporting",
      "Coordination"
    ],
    "extraction_quality": {
      "confidence_overall": "high",
      "warnings": []
    }
  }
}
