-- Who generated a positioning or cover letter run. 2026-10-07.
--
-- IN PLAIN ENGLISH
--
-- A coach can now run Positioning and Cover Letter for a client, from the job
-- on the coach's client page. The result is stored under the CLIENT's profile,
-- exactly like one the client ran, so the client sees it when they open the
-- job. These two columns record who actually ran it, so the client can read
-- "Generated by your coach" and the coach can tell their run from the client's.
--
-- Same vocabulary as the networking tables (20260903_network_attribution.sql):
-- created_by_role is 'client' or 'coach', created_by_id is the person who ran
-- it (a delegate coach records themselves, not their principal).
--
-- Rows from before this have NULL in both. NULL means "the client, before we
-- recorded it", because until now only the client could create these rows.
--
-- Additive: two nullable columns per table, no backfill, no rewrite. Safe to
-- run twice. Safe to apply to prod before the code: code that does not know
-- the columns never reads or writes them.
--
-- Reversibility:
--   ALTER TABLE positioning_runs DROP COLUMN IF EXISTS created_by_role, DROP COLUMN IF EXISTS created_by_id;
--   ALTER TABLE coverletter_runs DROP COLUMN IF EXISTS created_by_role, DROP COLUMN IF EXISTS created_by_id;

ALTER TABLE positioning_runs
  ADD COLUMN IF NOT EXISTS created_by_role TEXT,
  ADD COLUMN IF NOT EXISTS created_by_id UUID REFERENCES client_profiles(id) ON DELETE SET NULL;

ALTER TABLE coverletter_runs
  ADD COLUMN IF NOT EXISTS created_by_role TEXT,
  ADD COLUMN IF NOT EXISTS created_by_id UUID REFERENCES client_profiles(id) ON DELETE SET NULL;

ALTER TABLE positioning_runs DROP CONSTRAINT IF EXISTS positioning_runs_created_by_role_check;
ALTER TABLE positioning_runs
  ADD CONSTRAINT positioning_runs_created_by_role_check
  CHECK (created_by_role IS NULL OR created_by_role IN ('client', 'coach'));

ALTER TABLE coverletter_runs DROP CONSTRAINT IF EXISTS coverletter_runs_created_by_role_check;
ALTER TABLE coverletter_runs
  ADD CONSTRAINT coverletter_runs_created_by_role_check
  CHECK (created_by_role IS NULL OR created_by_role IN ('client', 'coach'));

NOTIFY pgrst, 'reload schema';
