// lib/positioning/v2/phase2/types.ts
//
// Shared types for the Positioning v2 Phase 2 (Resume Reframing Workflow).
// All Phase 2 lib files (itemPopulator, resumeComposer, aiClient,
// groundingValidator) import from here. The phase2_runs schema in
// supabase/migrations/20260516_phase2_runs.sql must stay in lockstep with
// PhaseTwoRunRow + PhaseTwoRunInsertPayload defined below.
//
// FRD: docs/Features/positioning-phase2-frd.md (§6.1 schema, §6.3 state)
// Design ref: docs/Features/positioning-design-reference-v2.md
// Parent types: lib/positioning/v2/types.ts (Case, JobfitResultJson,
//               CaseSpecificData, PositioningRunV2Row)
//
// Pure types only — no runtime values, no logic.

import type { Case } from "@/lib/positioning/v2/types"

// Re-export Case so phase2 callers can import everything from one module.
// Pure pass-through — parent types.ts remains the source of truth.
export type { Case } from "@/lib/positioning/v2/types"

// ============================================================================
// phase2_runs.status literal union
// ============================================================================

/**
 * Lifecycle status of a phase2_run. Mirrors the CHECK constraint in
 * supabase/migrations/20260516_phase2_runs.sql.
 *
 * Conceptually independent of PositioningRunV2Status on the parent
 * positioning_runs_v2 table even though the values happen to match —
 * the two can diverge in the future without coupling.
 */
export type PhaseTwoRunStatus = "in_progress" | "completed" | "abandoned"

// ============================================================================
// PhaseTwoItem — discriminated union over headline / bullet / gap
// ============================================================================

/**
 * Item type discriminator. Matches Pattern A (headline), Pattern B (bullet),
 * Pattern C (gap) from FRD §5.3.
 */
export type PhaseTwoItemType = "headline" | "bullet" | "gap"

/**
 * Headline reframe item (Pattern A). SIGNAL generates 1-3 option drafts;
 * user picks one, types an override, or declines.
 *
 * Field lifecycle:
 *   - On populator emit: draft_options=[], selected_draft_index=null,
 *     user_override_text=null, final_text=null, decision flags all false
 *   - On first /draft call: draft_options populated with 1-3 strings
 *   - On /decide accept: selected_draft_index set (or user_override_text
 *     set if user typed their own), final_text set to the resolved
 *     content, accepted=true, decided_at set
 */
export type PhaseTwoHeadlineItem = {
  id: string
  type: "headline"
  label: string
  /** Current headline text from the resume being reframed. */
  original: string
  /** 1-3 reframed options generated by SIGNAL. Empty until first /draft. */
  draft_options: string[]
  /** Index into draft_options. Null until /decide accept. */
  selected_draft_index: number | null
  /** User's manually-typed headline if they chose to override. Null otherwise. */
  user_override_text: string | null
  /**
   * Final accepted text after /decide accept fires. Source of truth for
   * resumeComposer. Null at populator emit, set on accept (from selected
   * draft, user_override_text, or edited_text per FRD §6.5.4).
   */
  final_text: string | null
  accepted: boolean
  declined: boolean
  skipped: boolean
  /** True if accept came via manual-entry mode (§6.9.1 grounding bypass). */
  manual_entry: boolean
  /** ISO8601 timestamp set when any decision flag flips to true. */
  decided_at: string | null
}

/**
 * Bullet reframe item (Pattern B). SIGNAL asks a targeted question about
 * the original bullet; user answers; SIGNAL drafts a reframed bullet from
 * the answer.
 *
 * Field lifecycle:
 *   - On populator emit: question_asked may be null or pre-populated by
 *     populator (FRD §6.6 shows question_asked being set in /draft handler;
 *     populator may also pre-generate). Modeled as nullable for safety.
 *   - user_response and draft populated on first /draft call
 *   - On /decide accept: final_text set (from draft or edited_text),
 *     decision flags set
 */
export type PhaseTwoBulletItem = {
  id: string
  type: "bullet"
  label: string
  /** The original bullet text being reframed. */
  original_bullet: string
  /** JD excerpt that motivated this recommendation. */
  jd_context: string
  /** SIGNAL's targeted question. Null until populator or first /draft sets it. */
  question_asked: string | null
  /** User's typed response to question_asked. Null until they answer. */
  user_response: string | null
  /** SIGNAL's reframed bullet draft. Null until first /draft. */
  draft: string | null
  /**
   * Final accepted text after /decide accept fires. Source of truth for
   * resumeComposer. Null at populator emit, set on accept (from selected
   * draft, user_override_text, or edited_text per FRD §6.5.4).
   */
  final_text: string | null
  accepted: boolean
  declined: boolean
  skipped: boolean
  manual_entry: boolean
  decided_at: string | null
}

/**
 * Gap discussion item (Pattern C). SIGNAL formulates a probing question
 * about a missing JD requirement; user answers (or skips); SIGNAL drafts
 * a new bullet or skill addition.
 *
 * Unlike Pattern B, gap items have no original text (the gap is by
 * definition missing content) — gap_description describes what the JD
 * is asking for that the resume doesn't address.
 *
 * Field lifecycle: matches Pattern B — question_asked starts null and is
 * populated by populator or first /draft call; user_response and draft
 * populated on first /draft after user answers; final_text set on /decide
 * accept (from draft or edited_text).
 */
export type PhaseTwoGapItem = {
  id: string
  type: "gap"
  label: string
  /** Description of the missing JD requirement. */
  gap_description: string
  /** JD excerpt anchoring the gap. */
  jd_context: string
  /** SIGNAL's probing question grounded in resume evidence. Null until populator or first /draft sets it. */
  question_asked: string | null
  /** User's typed response. Null until they answer (or null forever if skipped). */
  user_response: string | null
  /** SIGNAL's new-bullet draft. Null until /draft after user_response set. */
  draft: string | null
  /**
   * Final accepted text after /decide accept fires. Source of truth for
   * resumeComposer. Null at populator emit, set on accept (from selected
   * draft, user_override_text, or edited_text per FRD §6.5.4).
   */
  final_text: string | null
  accepted: boolean
  declined: boolean
  skipped: boolean
  manual_entry: boolean
  decided_at: string | null
}

/**
 * Discriminated union over all three item variants. Consumers narrow on
 * `type` to access variant-specific fields:
 *
 *   if (item.type === "headline") { item.draft_options ... }
 *   else if (item.type === "bullet") { item.original_bullet ... }
 *   else { item.gap_description ... }
 */
export type PhaseTwoItem =
  | PhaseTwoHeadlineItem
  | PhaseTwoBulletItem
  | PhaseTwoGapItem

// ============================================================================
// PhaseTwoState — top-level state JSONB shape
// ============================================================================

/**
 * Outcome of the workflow-completion decision the user makes when offered
 * "Save this as a new persona?" (FRD §5.5 / §6.5.5).
 *
 * TBD: the FRD example in §6.3 shows completion_decision as null, but the
 * field is not formally defined elsewhere. Modeling as a literal union
 * matching the /complete request's save_as_persona boolean. Revisit if
 * the FRD adds a third state (e.g., "deferred").
 */
export type PhaseTwoCompletionDecision = "saved" | "discarded"

/**
 * Full state JSONB stored on phase2_runs.state. Per FRD §6.3.
 *
 * Field semantics:
 *   - items: the recommended changes the user works through
 *   - current_section_id: which item the user has open (for resume on
 *     pause). Null on first entry / after returning to selection screen.
 *   - selection_screen_seen: flips true on first /draft or /decide call
 *   - completion_offered: flips true when "I'm done" or all-items-decided
 *     state surfaces the persona save prompt
 *   - completion_decision: set on /complete; null until then
 *   - ai_cost_cap_hit_at: ISO8601 timestamp; only present if AI cost cap
 *     (FRD §6.12) was hit during this run. Surfaced in error handling
 *     per FRD §6.9.
 */
export type PhaseTwoState = {
  items: PhaseTwoItem[]
  current_section_id: string | null
  selection_screen_seen: boolean
  completion_offered: boolean
  completion_decision: PhaseTwoCompletionDecision | null
  ai_cost_cap_hit_at?: string
}

// ============================================================================
// DB row shape
// ============================================================================

/**
 * Full row shape returned by SELECT * on phase2_runs. Mirrors the schema
 * in supabase/migrations/20260516_phase2_runs.sql.
 *
 * Schema and this type must stay in lockstep. CHECK enum lists in the
 * migration mirror the literal unions defined here:
 *   - case_letter ↔ Case ('A' | 'B' | 'C')
 *   - status ↔ PhaseTwoRunStatus
 */
export type PhaseTwoRunRow = {
  id: string
  positioning_run_id: string
  profile_id: string
  persona_id: string
  case_letter: Case
  state: PhaseTwoState
  /** Composed revised resume. Null until user accepts first item. */
  revised_resume_text: string | null
  /** Set only when user opts to save revised resume as a new persona. */
  new_persona_id: string | null
  status: PhaseTwoRunStatus
  /** AI generation cost accumulated for this run, in cents. Capped per §6.12. */
  ai_cost_cents: number
  /** ISO8601 timestamp. */
  created_at: string
  /** ISO8601 timestamp. */
  updated_at: string
  /** ISO8601 timestamp. Null until status='completed'. */
  completed_at: string | null
}

/**
 * Payload for INSERT into phase2_runs. Excludes DB-managed fields
 * (id, created_at, updated_at, completed_at) and optional fields with
 * DB defaults:
 *   - state: DB default '{}'::jsonb; in practice populator emits real state
 *   - status: DB default 'in_progress'
 *   - ai_cost_cents: DB default 0
 *   - revised_resume_text, new_persona_id: nullable
 */
export type PhaseTwoRunInsertPayload = {
  positioning_run_id: string
  profile_id: string
  persona_id: string
  case_letter: Case
  /** Populator emits initial state; defaulting to '{}' would skip items. */
  state: PhaseTwoState
  revised_resume_text?: string | null
  new_persona_id?: string | null
  status?: PhaseTwoRunStatus
  ai_cost_cents?: number
}
